name: Changelog / Update Unreleased

on:
  pull_request:
    branches: [development]
    types: [closed]

permissions:
  contents: write

jobs:
  changelog:
    uses: kanegae/github-actions-auto-changelog/.github/workflows/changelog-unreleased-reusable.yml@development
    with:
      unreleased_branch: development
      workflow_repository: kanegae/github-actions-auto-changelog
      workflow_ref: development