name: Changelog / Generate Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  changelog:
    uses: kanegae/github-actions-auto-changelog/.github/workflows/changelog-release-reusable.yml@development
    with:
      release_branch: master
      workflow_repository: kanegae/github-actions-auto-changelog
      workflow_ref: development